Feature/connecting sql alchemy
Studio-Yandex-Practicum/RandomCoffeeBot pull request #10
Opened 2023-07-19 16:39 UTC by bannybaks

1. Alembic is connect

> Changes alembic.ini (path to migration scripts, template used to generate migration files), env.py (config.set_main_option; target_metadata);

2.  File *.python-version and requirements.py excluded from upload

> The requirements.py function is delegated to poetry

4. Container with Postgres database prepared

5. Prepared a script with commands for working with the cotainer

6. Added dependencies to poetry configuration, generate service file to run poetry

7. Create global project config

8. Described function create session

9.  Described base class for models

2023-07-19 23:17 UTC, NiKuma0 requested changes

2023-07-19 23:17 UTC, NiKuma0 commented on src/core/db/session.py
> +Base = declarative_base()
Это не нужно для новой версии sqlalchemy...

2023-07-19 23:17 UTC, NiKuma0 commented on src/core/db/session.py
> +AsyncSessionLocal = sessionmaker(engine, class_=AsyncSession)
функция `sessionmaker` возвращает не сессию, а фабрику (функция/класс который создает сессию). Поменяй название и помести в функцию `get_async_session`

2023-07-19 23:17 UTC, NiKuma0 commented on src/settings.py
> +    description: str
Этого не надо.

2023-07-19 23:17 UTC, NiKuma0 commented on src/settings.py
> +    class Config:
Класс конфигов (или мета классы) всегда находится ниже всех методов и атрибутов.

2023-07-19 23:17 UTC, NiKuma0 commented on src/settings.py
> +        env_file = ".env"
В проде не будет env_file, этот конфиг только все поломает) Добавь переменную `TESTING` и в случае `True` добавь env_file.

2023-07-19 23:17 UTC, NiKuma0 commented on src/settings.py
> +        env_file_encoding = "utf-8"
Не думаю что это стоит явно указывать...

2023-07-19 23:17 UTC, NiKuma0 commented on infra/Makefile
Обычно Makefile в корень проекта ставят.

2023-07-19 23:17 UTC, NiKuma0 commented on infra/Makefile
> +	sudo rm -fr postgres_data
Что тут удаляется?) Насколько я вижу - postgres_data это docker volume, оно не так чистится...

2023-07-19 23:17 UTC, NiKuma0 commented on src/core/db/models.py
> +
Сразу добавь `id`, `created_at` и `udpated_at`

2023-07-20 16:31 UTC, bannybaks commented
1. Corrected library versions; not relevant in prod moved to the dev section
2. Removed declarative base class; declarative_base() irrelevant for SQLAlchemy version 2.0; sessionmaker now returns a factory; the factory is transferred to the manager
3. Removed redundant code; permutatoin in the Settings class; using *.env by trigger; explicit *.env encoding declaration removed
4. Added fields id, created_at, updated_at
5. Move the Makefile to the root; command to delete free volumes
6. Removing everything related to pydantic

2023-07-20 17:23 UTC, NiKuma0 requested changes
Расскажи как тестировал

2023-07-20 17:23 UTC, NiKuma0 commented on pyproject.toml
> +alembic = "^1.11.1"
Alembic должен быть в основной группе, не в dev

2023-07-20 17:23 UTC, NiKuma0 commented on src/settings.py
Убери весь этот файл

2023-07-20 17:38 UTC, bannybaks commented
Тестирование:

1.  Локально поднял контейнер с базой
2. Подключился к базе через расширение для VSCode `Database Client`
3. Проверил что есть подключение
4. Создал тестовую таблицу
5. Проверил наличие полей `id`, `created_at`, `updated_at`

2023-07-20 18:57 UTC, NiKuma0 commented
> Тестирование:
> 
> 1. Локально поднял контейнер с базой
> 2. Подключился к базе через расширение для VSCode `Database Client`
> 3. Проверил что есть подключение
> 4. Создал тестовую таблицу
> 5. Проверил наличие полей `id`, `created_at`, `updated_at`

Это ты БД postgres проверил, а как же sqlalchemy? Нужно попробовать сделать запрос, создать модельку для тестов и проверить работу alembic-а

2023-07-25 01:08 UTC, closed without merging