Feature/wednesday messages
Studio-Yandex-Practicum/RandomCoffeeBot pull request #114
Opened 2023-12-02 20:18 UTC by LyapkovAleksey

# Description

- Создал табличку match_review (необходимо применить миграцию)
- Добавил модель и репозиторий для MatchReview
- Добавил методы в notify_service и week_routine
- Добавил два вебхука для обработки ответа на рассылку

## Type of change

Пожалуйста, удалите варианты, которые не относятся к ПР-у.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Опишите, пожалуйста, тесты, которые вы провели для проверки ваших изменений. Предоставьте инструкции, чтобы мы могли воспроизвести их. Также укажите все необходимые детали конфигурации тестов.

- [ ] Для тестов необходимо несколько юзеров, зарегистрированных в таблице users и хотя бы одна запись в таблице usermatch. Нужно отправить в сообщения боту команду `/wednesday_message`. В ответ придёт сообщение рассылки, на котором будет две кнопки. При нажатии на любую должна появиться соответствующая запись в таблице match_review. 

# Checklist:

- [ ] Мой код соответствует code-style данного проекта
- [ ] Я провел самоанализ собственного кода
- [ ] Я внес соответствующие изменения в документацию

2023-12-02 21:03 UTC, NiKuma0 requested changes

2023-12-02 21:03 UTC, NiKuma0 commented on src/core/db/migrations/versions/6d584f53f8cf_.py
> +down_revision = "b0d3d8da38d0"
Почему id миграций сменились? Оставь как было.

Если были проблемы с миграциями, советую просто контейнер с БД почистить:
```
sudo docker compose down -v
```

2023-12-02 21:03 UTC, NiKuma0 commented on src/core/db/models.py
> +    NO_ANSWER = "NO_ANSWER"
В чем разница между `NO` и `NO_ANSWER`?

2023-12-04 07:49 UTC, LyapkovAleksey commented on src/core/db/models.py
> +    NO_ANSWER = "NO_ANSWER"
Слушай, а может вообще убрать `NO_ANSWER`? А значение по умолчанию сделать null для этой колонки. По идее, когда мы будем закрывать встречи на неделе, если кто-то не ответил, мы создадим запись со значением по умолчанию и всё. Тогда если кто-то что-то ответил, у нас есть только два варианта, если ничего не ответили, колонка null по дефолту

2023-12-04 18:58 UTC, NiKuma0 approved these changes

2023-12-04 19:22 UTC, merged