Feature/pydantic settings
Studio-Yandex-Practicum/RandomCoffeeBot pull request #27
Opened 2023-07-28 13:21 UTC by gavingreenhorn

- add db / bot configs to the Settings object
- injected the latter into db session & bot initializers

2023-07-28 16:18 UTC, NiKuma0 requested changes

2023-07-28 16:18 UTC, NiKuma0 commented on src/depends.py
> +settings = Provide[Container.settings]
Так не нужно делать, это работать не будет.

2023-07-28 16:18 UTC, NiKuma0 commented on src/settings.py
> +    ssl_verify: bool
Переменные окружения должны быть записаны капсом (т.к. по сути константы, и их принято так записывать). 
Посмотри как это сделано в других проектах, [например ](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/develop/src/core/settings.py)

2023-07-28 16:18 UTC, NiKuma0 commented on src/core/db/session.py
>  async_session_maker = async_sessionmaker(engine, expire_on_commit=False)
Тут не надо ничего трогать, этого файла скоро не будет.

2023-07-28 16:18 UTC, NiKuma0 commented on src/bot/bot.py
>  def init_bot():
Пусть init_bot будет принимать settings. 
```suggestion
def init_bot(settings: Settings = Provide[Container.settings]):
```

2023-07-28 16:18 UTC, NiKuma0 commented on src/settings.py
> +    ssl_verify: bool
Также добавь значения по дефолту.

2023-07-29 12:42 UTC, NiKuma0 requested changes
Совсем не хватает комментариев в сеттингах, их не должно быть много, но при этом чтоб было понятно что `BOT_TOKEN` это токен mattermost-а. Посмотри как это сделано в "Ламая барьеры"

2023-07-29 12:42 UTC, NiKuma0 commented on src/settings.py
> +    DATABASE_URL: PostgresDsn = "postgresql+asyncpg://postgres:postgres@localhost:5432/postgres"
Это зачем? Посмотри как это сделано в других проектах - это ссылка формируется из других настроек.

2023-07-29 12:42 UTC, NiKuma0 commented on src/settings.py
> +    DB_ENGINE: str = "postgresql+asyncpg"
Не думаю что это понадобиться...

2023-07-29 12:42 UTC, NiKuma0 commented on src/settings.py
> +    DB_NAME: str = "postgres"
Лучше назвать также как в контейнере postgres -  `POSTGRES_DB`

2023-07-29 12:42 UTC, NiKuma0 commented on src/settings.py
> +    MATTERMOST_URL: HttpUrl = "http://mattermost"
```suggestion
    MATTERMOST_URL: HttpUrl = "http://localhost"
```

2023-07-29 12:42 UTC, NiKuma0 commented on src/settings.py
> +    LOGGER_NAME: str = "root"
Это не очень хорошая практика - оставь имя логгера в объявлении логгера.

2023-07-29 12:42 UTC, NiKuma0 commented on src/settings.py
> +    model_config = SettingsConfigDict(extra="ignore", case_sensitive=True, env_file=ROOT_FOLDER / ".env")
А что если файла `.env` не будет?

2023-07-29 12:42 UTC, NiKuma0 commented on src/constants.py
> +ROOT_FOLDER = Path(__file__).parent.parent
Лучше перенеси это в `settings.py`

2023-07-29 12:42 UTC, NiKuma0 commented on src/bot/bot.py
> +            SSL_VERIFY=settings.ssl_verify,
Тут капс забыл - `settinsg.BOT_TOKEN`

2023-07-30 17:34 UTC, gavingreenhorn commented on src/constants.py
> +ROOT_FOLDER = Path(__file__).parent.parent
Есть применение этой переменной и до инициализации Settings.
Например - для проверки наличия .env файла (как сделано в том же "Ломая барьеры")

2023-07-30 17:40 UTC, gavingreenhorn commented on src/constants.py
> +ROOT_FOLDER = Path(__file__).parent.parent
А, ну если ты имешь в виду только в файл перенести, тогда да.

2023-07-30 19:40 UTC, NiKuma0 requested changes

2023-07-30 19:40 UTC, NiKuma0 commented on src/settings.py
> +    LOGGER_NAME: str = "root"
Не могу из-за этого задержать ПР, но вообще, слишком много комментариев - держи в голове, что имя переменной тоже несет полезную информацию (лучше сделать более подробное имя переменной чем добавить комментарий), а значит что-то на подобие "Токен бота" над переменой `BOT_TOKEN` будет просто бесполезно.

Хорошо получилось с переменными postgres - хоть комментарий может показаться лишним, зато он визуально отделяет настройки БД от чего-то еще. Важно не только объяснить что это за переменная, но и визуально отделить от других, так будет легче ориентироваться. Сделай также со всем остальным, тут получится `# Mattermost Bot settings` и `# Logging settings`

2023-07-30 19:40 UTC, NiKuma0 commented on src/settings.py
> +(ENV_FILE := ROOT_FOLDER / ".env").touch()
Его не нужно создавать... У нас будут браться переменные не только из файла, но и из окружения. Второй вариант будет работать в контейнере, там такой файл не нужен.

Опять же, подобную логику можно увидеть и позаимствовать из других проектах.

2023-07-31 18:15 UTC, NiKuma0 approved these changes

2023-07-31 18:15 UTC, merged