Написаны AbstractRepository и основа UserRepository
Studio-Yandex-Practicum/RandomCoffeeBot pull request #28
Opened 2023-07-28 23:03 UTC by oladushkin

Взял и доработал функции из Ломая барьеры, ProChairity2.
Проверял каждую функцию с помощью скрипта `create_table.py`.
Создавал обьект `UserRepository` и в него передавал `sessionmaker, потом делал запросы с помощью этого объекта.
Объекты создаются и обновляются.

2023-07-28 23:10 UTC, NiKuma0 requested changes

2023-07-28 23:10 UTC, NiKuma0 commented on src/core/db/repository/base.py
> +        instance = await self._sessionmaker.execute(select(self._model).where(self._model.id == instance_id))
Это не будет работать... Посмотри задачу внимательнее - тут нет ничего что я описал в ней. 

P.S. В следующий раз потестируй.

2023-07-28 23:52 UTC, oladushkin commented on src/core/db/repository/base.py
> +        instance = await self._sessionmaker.execute(select(self._model).where(self._model.id == instance_id))
При тестировании в этой функции появлялась ошибка `'AsyncSession' object is not callable`, этот запрос я взял из ProChairity2. И сразу все get-запросы выполнялись и при передачи неправильного `id` вызывалось исключение.
В комментарии к PR я указал что тестировал каждый запрос к БД отдельно. (разворачивал контейнер БД и делал запросы).

2023-07-29 22:12 UTC, NiKuma0 requested changes

2023-07-29 22:12 UTC, NiKuma0 commented on src/core/db/repository/base.py
> +from src.core import exceptions
У нас же нет такого модуля...

2023-07-29 23:18 UTC, NiKuma0 approved these changes

2023-07-29 23:18 UTC, merged