Feature/session.py DI include
Studio-Yandex-Practicum/RandomCoffeeBot pull request #29
Opened 2023-07-29 15:11 UTC by bannybaks

**What is done:**

- [ ]  Delete file session.py, move functionality to file depends.py;
- [ ]  Get engine and async_sessionmaker from DI container;

**How it was tested:**

1. depends.py module loaded interactively;
2. created two objects and checked: 
     - objects are created;
     - objects have different id;
     - objects of type AsyncSession.

2023-07-29 17:21 UTC, NiKuma0 requested changes

2023-07-29 17:21 UTC, NiKuma0 commented on src/depends.py
> +    async_session_maker = providers.Singleton(async_sessionmaker, engine, expire_on_commmit=False)
Давай просто `sessionmaker`

2023-07-29 17:21 UTC, NiKuma0 commented on src/depends.py
> +    AsyncSessionMaker = async_sessionmaker[AsyncSession]
Плохое место выбрал) Сейчас убери - подумал, что лучше будет это добавить в рамках другой задачи.

2023-07-30 08:31 UTC, bannybaks commented on src/depends.py
> +    async_session_maker = providers.Singleton(async_sessionmaker, engine, expire_on_commmit=False)
в вызове провайдера использовать `sessionmaker`, или `async_session_maker` заменить на `sessionmaker`?

2023-07-30 11:30 UTC, NiKuma0 commented on src/depends.py
> +    async_session_maker = providers.Singleton(async_sessionmaker, engine, expire_on_commmit=False)
```suggestion
    sessionmaker = providers.Singleton(async_sessionmaker, engine, expire_on_commmit=False)
```

2023-07-30 19:41 UTC, NiKuma0 approved these changes

2023-07-30 19:41 UTC, merged