Добавил Alembic
Studio-Yandex-Practicum/RandomCoffeeBot pull request #32
Opened 2023-07-31 09:33 UTC by tmbkv

Добавил Alembic. В файле settings.py добавил переменную settings, чтобы импортировать настройки в файл env.py

2023-08-01 10:53 UTC, NiKuma0 commented on src/settings.py
> +settings = Settings()
У нас сеттинги будут в DI контейнере, такая конструкция не очень... Можно перенести эту строку в `env.py`, потом мб что-то по лучше придумаем...

2023-08-01 15:09 UTC, tmbkv commented
Сделал еще два коммита, в одном изменил файл env.py, в другом вернул файл settings.py в первоначальный вид

2023-08-02 23:21 UTC, NiKuma0 requested changes

2023-08-02 23:21 UTC, NiKuma0 commented on alembic/env.py
> +# settings = Settings()
Это работать не будет...

2023-08-03 13:19 UTC, NiKuma0 requested changes
Поправь конфликт. В идеале ты не должен был трогать `settings.py`

2023-08-03 13:19 UTC, NiKuma0 commented on alembic/env.py
> +from src.settings import settings
У нас же нет никакого объекта `settings` в этом модуле и не должно быть. Я тебя попросил его объявить здесь - если есть вопросы по ревью, спрашивай.

2023-08-03 14:33 UTC, NiKuma0 requested changes

2023-08-03 14:33 UTC, NiKuma0 commented on alembic/env.py
> +config.set_main_option("sqlalchemy.url", Settings.database_url)
Это не похоже на рабочий код. Потестируй.

2023-08-04 06:50 UTC, closed without merging