Пофиксил логгирование
Studio-Yandex-Practicum/RandomCoffeeBot pull request #47
Opened 2023-08-06 14:51 UTC by hive937

- Добавил вызов init_logging() в run.py
- Добавил библиотеки rich и structlog в pyproject.toml
- Перенес logger.py в /core и переименовал его в logging.py

2023-08-06 14:59 UTC, NiKuma0 requested changes
В целом всё хорошо. Убери `Provide` из функции `init_logging` и [добавь новые библиотеки в requirements.txt ](https://python-poetry.org/docs/cli/#export)/

2023-08-06 14:59 UTC, NiKuma0 commented on src/run.py
> +    logging.info("Application started")
Это работает...? Используй structlog - `logger = structlog.get_logger()` [как в документации](https://www.structlog.org/en/stable/getting-started.html#your-first-log-entry)

2023-08-06 19:56 UTC, hive937 reviewed
Поправил замечания
- Убрал лишние импорты
- Обновил requirements
- Изменил версию Rich на две пониже (не хотело ставить самую последнюю)
- Поправил логирование в run.py (сделал через structlog)

2023-08-07 00:58 UTC, NiKuma0 requested changes

2023-08-07 00:58 UTC, NiKuma0 commented on requirements.txt
> +    --hash=sha256:00ad4b6f185ec67f3e6562e8a1d2b69660be43070bd0ef6fcec5211154c7df67 \
Хеш не нужен `--without-hashes`

2023-08-07 00:58 UTC, NiKuma0 commented on src/core/logging.py
> +def init_logging(settings: Settings, name: str = "log.log"):
Кажется name больше не нужно.
```suggestion
def init_logging(settings: Settings):
```

2023-08-07 00:58 UTC, NiKuma0 commented on src/run.py
> +    log = structlog.get_logger()
логгер объяви в корне файла, в функции не нужно.

2023-08-07 01:03 UTC, NiKuma0 commented
> * Изменил версию Rich на две пониже (не хотело ставить самую последнюю)

Почему? Ты же не бету ставишь. Можно смело использовать последнюю стабильную версию, это рекомендовано, так будет меньше багов. Есть только одно исключение - если перестали поддерживать функции которыми мы пользуемся, тогда можно подумать.

2023-08-08 19:26 UTC, hive937 commented
- Поправил строки, где подтягиваются данные из settings
- Добавил настройки в init_logging (container.settings)

2023-08-09 13:27 UTC, NiKuma0 approved these changes
Поправь конфилкт, и можно мержить.

2023-08-09 17:34 UTC, hive937 commented
Скрин работы логов скину завтра

2023-08-10 08:42 UTC, merged