Made admin registration
Studio-Yandex-Practicum/RandomCoffeeBot pull request #53
Opened 2023-08-14 06:50 UTC by hive937

Реализовал функцию регистрации админа

2023-08-14 14:28 UTC, NiKuma0 requested changes

2023-08-14 14:28 UTC, NiKuma0 commented on src/bot/plugins.py
> +class Admin(Plugin):
Перемести в отдельный файл `src/bot/plugins/admin.py`

2023-08-14 14:28 UTC, NiKuma0 commented on src/bot/plugins.py
> +        await admin_registration(username=message.sender_name, user_id=message.user_id)
Совсем не то. Тут не должна быть регистрация, только проверка есть ли у пользователя права вызвать эту функцию.

2023-08-14 14:28 UTC, NiKuma0 commented on src/core/db/models.py
> +    status: Mapped[StatusEnum] = mapped_column(nullable=False)
Админу не понадобится статус.

2023-08-14 14:28 UTC, NiKuma0 commented on src/settings.py
> +    ADMIN: str
Сеттинг добавил, но нигде не используешь? Так лучше не делать.

2023-08-16 08:30 UTC, NiKuma0 requested changes

2023-08-16 08:30 UTC, NiKuma0 commented on src/bot/plugins.py
> +
Тут некоторые импорты нигде не используются. Убери.

2023-08-16 08:30 UTC, NiKuma0 commented on src/bot/plugins/admin.py
> +        admin_id = AdminRepository.get_admin_id(self, settings)
Воспользуйся DI контейнером, не просто же так ты поставил `@inject` - вот [документация](https://python-dependency-injector.ets-labs.org/) и [пример из нашего кода](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBot/blob/develop/src/bot/plugins.py#L29). Не забудь добавить репозиторий и сервис в контейнер `src/depends.py`

Не нужно использовать репозиторий изнутри хендлера, посмотри [нашу доку](https://sixth-lathe-416.notion.site/Wiki-ded87ffa31a74c7bbd3e3e71483df1a4) в "Описание принципов закладываемых в архитектуру нашего приложения".

2023-08-16 08:30 UTC, NiKuma0 commented on src/core/db/repository/admin.py
> +            instance = await session.scalar(select(self.user_id).where(self.username == settings.ADMIN))
Совсем не то... Сделай проще - в БД у тебя будут хранится только админы. Если у кого-то username такой же как в настройках, создай в БД новую запись, если нет - просто проверь, есть ли такой id. Эта логика должна быть в сервисах, запросы БД в репозиториях.

2023-08-16 16:30 UTC, NiKuma0 requested changes
Добавь тайп хинтинги, это важно)

2023-08-19 12:48 UTC, NiKuma0 requested changes
Скорее всего ошибка была из-за неправильного расположения `@inject`. Ещё может быть причиной не хватка `__init__.py` в `src/` папке. 

Обновись и поправь конфликт, может это тоже поможет.

2023-08-19 12:48 UTC, NiKuma0 commented on src/bot/plugins/admin.py
> +    async def admin(self, message: Message, admin_service: AdminService = Provide[Container.admin_service]):
Не там стоит `inject` - должен быть обязательно первым.  
```suggestion
    @listen_to("Admin", re.IGNORECASE)
    @inject
    async def admin(self, message: Message, admin_service: AdminService = Provide[Container.admin_service]):
```

2023-08-19 12:48 UTC, NiKuma0 commented on src/depends.py
> +    default_admin = settings.provided.ADMIN
Можно обойтись без этой переменной.

2023-08-19 12:48 UTC, NiKuma0 commented on src/depends.py
> +    admin_repository = providers.Factory(AdminRepository, sessionmaker=sessionmaker)
Раздели комментариями зависимости - чтобы были  `# Settings`, `# Database connection`, `# Repositories` и `# Services`

2023-08-19 12:48 UTC, NiKuma0 commented on src/run.py
> +    # init_logging(container.settings())
Можно удалить комментарии.

2023-08-19 12:48 UTC, NiKuma0 commented on src/settings.py
> +    ADMIN: str
Лучше назови как `ADMIN_USERNAME`

2023-08-19 12:48 UTC, NiKuma0 commented on src/bot/plugins/__init__.py
Здесь добавь импорт плагинов, чтобы было удобно:
```python
from .admin import BotAdmin

__all__ = (
    "BotAdmin",
)

```
Теперь этот плагин можно импортировать таким образом: `from src.bot.plugins import BotAdmin`

2023-08-19 14:13 UTC, hive937 commented
Закоммитил рабочую версию

2023-08-19 18:08 UTC, NiKuma0 requested changes

2023-08-19 18:08 UTC, NiKuma0 commented on src/bot/services/admin.py
> +        return self._admin_username
Зачем эта функция?

2023-08-19 18:08 UTC, NiKuma0 commented on src/bot/services/admin.py
> +        await self.add_admin_if_in_settings(username, instance)
А разве нельзя получить username через instance (`instance.username`)?

2023-08-19 18:08 UTC, NiKuma0 commented on src/core/db/repository/admin.py
> +        return self.create(instance)
Зачем эта функция? Не похоже что она будет работать...

2023-08-19 18:08 UTC, NiKuma0 commented on src/bot/plugins/admin.py
> +        if message.sender_name == admin_service.get_default_admin_username():
А это условие зачем? Ты же в `check_if_admin` все проверяешь.

2023-08-19 18:53 UTC, hive937 commented on src/core/db/repository/admin.py
> +        return self.create(instance)
Почему не будет? В репозитории регистрации, например, у нас есть такая же строка https://github.com/Studio-Yandex-Practicum/RandomCoffeeBot/blob/develop/src/core/db/repository/user.py#L19

2023-08-20 11:31 UTC, NiKuma0 commented on src/core/db/repository/admin.py
> +        return self.create(instance)
@hive937 ты вызываешь функцию `create` внутри функции `create` - это рекурсия, и при этом бесконечная) Если хочешь обратиться к классу радетелю использую `super().create`, но в этом нет смысла - никакой доп логики не добавляется.

2023-08-20 18:50 UTC, hive937 commented on src/core/db/repository/admin.py
> +        return self.create(instance)
Дошло

2023-08-21 13:07 UTC, NiKuma0 approved these changes
Уже гораздо лучше, в целом можно мержить, но нужно поправить конфликт. Есть какие-то проблемы с этим? Пиши в пачку. 

У нас добавился линтер `mypy` - он не пропустит этот код т.к. нет аннотаций, их нужно поставить везде.

2023-08-21 13:07 UTC, NiKuma0 commented on src/bot/services/admin.py
> +            await self._admin_repository.create(instance)
Не совсем то что я имел в виду: 
```suggestion
    async def add_admin_if_in_settings(self, instance: Admin):
        if instance.username == self._admin_username:
            await self._admin_repository.create(instance)
```

2023-08-21 17:39 UTC, merged