Documentation/readme
Studio-Yandex-Practicum/RandomCoffeeBot pull request #64
Opened 2023-08-18 10:08 UTC by Linnaip

# Description

Если нужно что-то дополнить по внесённым изменениям.

## Type of change

Пожалуйста, удалите варианты, которые не относятся к ПР-у.

- [ ] Documentation (опечатки, примеры кода или любое обновление документации)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Опишите, пожалуйста, тесты, которые вы провели для проверки ваших изменений. Предоставьте инструкции, чтобы мы могли воспроизвести их. Также укажите все необходимые детали конфигурации тестов.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] Мой код соответствует code-style данного проекта
- [ ] Я провел самоанализ собственного кода
- [ ] Я внес соответствующие изменения в документацию

2023-08-18 12:13 UTC, Linnaip commented
Сделал README.md

2023-08-18 13:18 UTC, NiKuma0 commented on src/bot/bot.py
Вот это мы вроде как уже поправили. Обновись)

2023-08-18 13:27 UTC, NiKuma0 commented on README.md
> +> Официальная документация: ```https://python-poetry.org/docs/```
Лучше сделать эту заметку под командой `poetry install`, еще лучше будет ссылка на инструкцию по установке poetry, с припиской "Если нет poetry, следуйте [инструкции по установке](https://python-poetry.org/docs/#installation)". Сделай ссылки колыбельными, еще лучше спрятать их в текст.

2023-08-18 13:27 UTC, NiKuma0 commented on README.md
> +> Шпаргалка: ```https://habr.com/ru/articles/593529/```
Шпаргалка устарела, там используется `pip install poetry`, это не рекомендованный способ установки.

2023-08-18 13:29 UTC, NiKuma0 commented on README.md
> +```
Это зачем?

2023-08-18 13:29 UTC, NiKuma0 commented on README.md
> -
Это оставь

2023-08-18 13:31 UTC, NiKuma0 commented on README.md
> +```
А если он уже есть?) Инструкция должна исключительно касаться нашего проекта, оставь это документации poetry, оставив ссылку на нужный блок, так будет точнее и более информативно.

2023-08-18 13:33 UTC, NiKuma0 commented on README.md
> +> Не используйте pip install poetry
Также, оставь это документации poetry. Может они вновь возобновят поддержку pip, кто знает)

2023-08-18 13:39 UTC, NiKuma0 commented on README.md
> +```
Добавь табы, чтобы этот блок кода был как-бы частью пункта. Как тут:
![image](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBot/assets/78080842/53f2457b-631d-4d8d-a5ec-d3ff892c183d) 
```suggestion

    ```
    poetry install
    ```
```
Сделай так же по всему файлу.

2023-08-18 13:41 UTC, NiKuma0 commented on README.md
> +Настройка .env
Это зачем?)

2023-08-18 13:41 UTC, NiKuma0 commented on README.md
> +1. Запустите open-source платформу Mattermost командой
В этом контейнере не только mattermost но и БД.

2023-08-18 13:42 UTC, NiKuma0 commented on README.md
> +> После нажатия Done, вы больше не сможете посмотреть Access Token
Это также оставь документации mattermost-а.

2023-08-18 13:43 UTC, NiKuma0 commented on README.md
> +http://localhost:8065
Сделай ссылку кликабельной - "После запуска контейнера, перейдите по [этой ссылке](http://localhost:8065)"

2023-08-18 13:44 UTC, NiKuma0 commented on README.md
> +1. Примените миграции базы данных
Миграции необходимо применить до запуска проекта `python src/run.py`

2023-08-18 13:46 UTC, NiKuma0 commented on README.md
> +python src/run.py
Эта команда будет также работать и на linux.

2023-08-22 10:13 UTC, NiKuma0 commented on README.md
> +  ```
Тут так и не поправил - добавь табы.

2023-08-22 10:13 UTC, NiKuma0 commented on README.md
> +6. Перейдите по гиперссылке "Integrations>Bot Accounts"
Давай это оставим документации mattermost-а. Юзер интерфейс может сильно поменяться, а обновлять этот readme никто не будет, зато ссылка еще долго не устареет)

2023-08-22 10:13 UTC, NiKuma0 commented on README.md
> +> Не выключайте контейнер с платформой
Какой контейнер, с какой платформой? Кажется стоит добавить это пояснение под пункт с запуском этого контейнера)

2023-08-22 10:13 UTC, NiKuma0 commented on README.md
> +  ```
Тут можно спокойно объединить эти пункты - оба варианта работают как и под linux/mac так и под windows.

2023-08-22 10:13 UTC, NiKuma0 commented on README.md
> +> Без это проект не будет работать
Вообще, это у нас баг, его нужно поправить) Это быстро станет не актуальным.

2023-08-22 10:13 UTC, NiKuma0 commented on README.md
> +  ```
Лучше создай файл `.env.example` и запиши туда все переменные (их можно подсмотреть в `src/settings.py`), а тут добавь ссылку на этот файл (`[скопируйте этот файл](./.env.example)`).

2023-08-23 11:13 UTC, NiKuma0 requested changes

2023-08-23 11:13 UTC, NiKuma0 commented on .env.example
> +LOG_ROOT: DirectoryPath = ROOT_FOLDER / "logs"
Это работать не будет - тестируй код пожалуйста). У .env файла нет никаких тайпингов как у питона.

2023-08-23 16:46 UTC, NiKuma0 approved these changes

2023-08-23 16:46 UTC, merged