added a table filling script
Studio-Yandex-Practicum/RandomCoffeeBot pull request #70
Opened 2023-08-23 18:01 UTC by Omen121

# Description

Если нужно что-то дополнить по внесённым изменениям.

## Type of change

Пожалуйста, удалите варианты, которые не относятся к ПР-у.

- [ ] Documentation (опечатки, примеры кода или любое обновление документации)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

# How Has This Been Tested?

Опишите, пожалуйста, тесты, которые вы провели для проверки ваших изменений. Предоставьте инструкции, чтобы мы могли воспроизвести их. Также укажите все необходимые детали конфигурации тестов.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ x] Мой код соответствует code-style данного проекта
- [x ] Я провел самоанализ собственного кода
- [ ] Я внес соответствующие изменения в документацию

2023-08-25 11:39 UTC, NiKuma0 requested changes
Гораздо легче было бы использовать DI контейнер и готовые функции из репозиториев (которые тоже легче подключать через DI контейнер). Добавь контейнер сейчас, чтобы в дальнейшем было проще расширять функционал.

2023-08-25 11:39 UTC, NiKuma0 commented on pyproject.toml
> +faker = "^19.3.0"
Эта библиотека должна быть в dev dependencies.

2023-08-25 11:39 UTC, NiKuma0 commented on fill_db.py
> +engine = create_async_engine(Settings().database_url)
Используй DI контейнер.

2023-08-25 11:39 UTC, NiKuma0 commented on fill_db.py
> +    users = await session.execute(User.__table__.select())
По хорошему используй репозиторий.

2023-08-28 18:05 UTC, Omen121 commented on fill_db.py
> +    users = await session.execute(User.__table__.select())
Оставил пока так, после создания сервиса подбора пар можно будет пофиксить

2023-08-30 14:03 UTC, NiKuma0 requested changes

2023-08-30 14:03 UTC, NiKuma0 commented on fill_db.py
> +    users = await session.execute(User.__table__.select())
Зачем ждать?)

2023-08-30 14:03 UTC, NiKuma0 commented on fill_db.py
> +    async with session_manager() as session:
Совсем не то... Добавил в вики блок про работу с DI, посмотри и поправь.

2023-08-30 14:03 UTC, NiKuma0 commented on src/core/db/db.py
> +from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
Этот файл не нужен, используй DI контейнер.

2023-09-04 16:02 UTC, Omen121 commented on fill_db.py
> +    users = await session.execute(User.__table__.select())
Добавил использование репозитория для создания пользователей и мэтчей

2023-09-04 16:03 UTC, Omen121 commented on fill_db.py
> +    async with session_manager() as session:
Поправил на основе конетейнера из существующего depends.py

2023-09-04 16:03 UTC, Omen121 commented on src/core/db/db.py
> +from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
Использовал)

2023-09-06 16:36 UTC, merged