Feature/matching service
Studio-Yandex-Practicum/RandomCoffeeBot pull request #79
Opened 2023-10-16 17:54 UTC by Qerced

# Description

Необходимо дописать логику работы сервиса, после проведения встреч.

## Type of change

Пожалуйста, удалите варианты, которые не относятся к ПР-у.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Для тестирования необходимо создать в базе пользователей со статусами ожидания встреч (если у них будут другие статусы, то сервис все равно отработает, но пар не появится). После написать боту `/match` и дождаться ответа об завершение работы. Результатом будут встречи со статусом ONGOING. При нечетном количестве участников,
один из них останется без пары и его статус ожидания не изменится (информация об этом будет отображена в логах). Сервис может подобрать новую пару, даже если участники не закроют предыдущую встречу. Подбор создается всегда уникальным и зависит от количества незакрытых встреч. Вопрос с закрытием встреч пока открыт.

# Checklist:

- [ ] Мой код соответствует code-style данного проекта
- [ ] Я провел самоанализ собственного кода
- [ ] Я внес соответствующие изменения в документацию

2023-10-17 01:03 UTC, NiKuma0 requested changes

2023-10-17 01:03 UTC, NiKuma0 commented on src/core/db/repository/usersmatch.py
> +                )
Про это я писал в другом ПР. Пользователи никак не привязаны к своим "местам". У нас могут быть две пары, которые будут считаться разными, но фактически одинаковыми:

```python

one = User(...)
two = User(...)


# Пользователь `one` и `two` могут заметчится два раза,
# просто потому-что в первый раз один стоял в поле `matched_user_one`,
# а во второй в поле `matched_user_two`
UsersMatch(matched_user_one=one, matched_user_two=two) == UsersMatch(matched_user_one=two, matched_user_two=one)  # Вернет False

```

2023-10-17 01:03 UTC, NiKuma0 commented on src/core/exceptions/exceptions.py
> +class NoUserFoundError(Exception):
Наверное нам не стоит из-за этого падать с ошибкой, ведь для того чтобы для кого-нибудь не нашлось пары, достаточно чтобы пользователей было нечетное кол-во, а это 50% шанс. Лучше это просто логировать.

2023-10-20 20:39 UTC, NiKuma0 reviewed
Поправь немного код стиль.

Расскажи, как тестировал?

2023-10-20 20:39 UTC, NiKuma0 commented on src/bot/services/matching.py
> +            if user_two := await self._user_repository.get_without_current(user_one):
Уменьши вложенность 
```suggestion
            if not (user_two := await self._user_repository.get_without_current(user_one)):
                return log.info(f"Невозможно создать пару для пользователя с id {user.id}.")
```

2023-10-20 20:39 UTC, NiKuma0 commented on src/core/db/repository/user.py
> +    async def get_without_current(self, user: User) -> User | None:
Теперь название функции не подходит.

2023-10-20 20:39 UTC, NiKuma0 commented on src/core/db/repository/user.py
> +                .filter(
Мы по всему проекту используем `.where()`

```suggestion
                .where(
```

2023-10-20 20:39 UTC, NiKuma0 commented on src/core/db/repository/user.py
> +                    or_(UsersMatch.matched_user_one != user.id, UsersMatch.matched_user_two != user.id),
```suggestion
                    (UsersMatch.matched_user_one != user.id) | (UsersMatch.matched_user_two != user.id),
```

2023-10-20 20:39 UTC, NiKuma0 commented on src/core/db/repository/usersmatch.py
> +                    )
Используй везде стандартные операторы, функции не нужно.
```suggestion
                    (
                        self._model.matched_user_one == user_one.id,
                        self._model.matched_user_two == user_two.id,
                    ) | (
                        self._model.matched_user_one == user_two.id,
                        self._model.matched_user_two == user_one.id,
                    )
```

Тут не уверен что конструкция будет работать, но посыл ясен.

2023-10-20 20:39 UTC, NiKuma0 commented on src/core/db/repository/usersmatch.py
> +                .filter(
```suggestion
                .where(
```

2023-10-20 20:39 UTC, NiKuma0 commented on src/bot/plugins/matching.py
> +    async def test(self, message: Message, usermatch: MatchingService = Provide[Container.matching_service]) -> None:
Используй интуитивное название.
```suggestion
    async def test(self, message: Message, matching_service: MatchingService = Provide[Container.matching_service]) -> None:
```

2023-10-20 20:39 UTC, NiKuma0 commented on src/bot/plugins/matching.py
> +    @listen_to("match", re.IGNORECASE)
```suggestion
    @listen_to("/match", re.IGNORECASE)
```

2023-10-21 23:21 UTC, NiKuma0 commented on src/core/db/repository/user.py
> +                    UsersMatch.id.is_(None)
Зачем проверка на id? Разве он не автоматом ставится на все `UsersMatch`?

2023-10-21 23:21 UTC, NiKuma0 commented on src/core/db/repository/user.py
> +                    | (UsersMatch.matched_user_two != user.id) & (UsersMatch.status != MatchStatusEnum.ONGOING)
```suggestion
                    | (UsersMatch.matched_user_two != user.id)
                    & (UsersMatch.status != MatchStatusEnum.ONGOING)
```

2023-10-21 23:37 UTC, Qerced commented on src/core/db/repository/user.py
> +                    UsersMatch.id.is_(None)
> Зачем проверять идентификатор? Разве он не автоматом появляется на всех `UsersMatch`?

Запрос возвращает None, если пользователи еще не участвовали во встречах. Поэтому приходится выбирать пару из тех у кого либо не было встреч, либо были и подходят по условию.

2023-10-22 17:40 UTC, NiKuma0 approved these changes

2023-10-22 17:40 UTC, merged