Add webhooks(problems)
Studio-Yandex-Practicum/RandomCoffeeBot pull request #83
Opened 2023-10-24 15:10 UTC by KlavaD

# Description

Проблема 1:
Не работают вебхуки. Прописала прямы урлы, оставила 20 секундный шедулер.
Проблема 2:
С вебхуками работает медленнее.

## Type of change

Пожалуйста, удалите варианты, которые не относятся к ПР-у.

- [ ] Documentation (опечатки, примеры кода или любое обновление документации)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Опишите, пожалуйста, тесты, которые вы провели для проверки ваших изменений. Предоставьте инструкции, чтобы мы могли воспроизвести их. Также укажите все необходимые детали конфигурации тестов.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] Мой код соответствует code-style данного проекта
- [ ] Я провел самоанализ собственного кода
- [ ] Я внес соответствующие изменения в документацию

2023-10-28 17:42 UTC, NiKuma0 requested changes

2023-10-28 17:42 UTC, NiKuma0 commented on src/bot/plugins/week_routine.py
> +        # )
Убери этот комментированный код. Для тестов, лучше создай команду `notify_all_users` которая будет запускать этот сервис сразу.

2023-10-28 17:42 UTC, NiKuma0 commented on src/endpoints.py
> +        return url  # TODO: Просто их плюсовать плохой вариант, найти лучше.
убери TODO

2023-10-28 17:42 UTC, NiKuma0 commented on src/endpoints.py
> +        return self.host_append("/hooks/no")
Просто `yes` и `no` плохая идея - таких кнопок может быть много. Переименуй, так чтобы описало что делает этот хук, а не на что откликается.

2023-10-28 17:42 UTC, NiKuma0 commented on src/settings.py
> +# from urllib.parse import urljoin
Тут также, убери комментарии.

2023-10-28 17:42 UTC, NiKuma0 commented on src/settings.py
> +    MM_SERVICESETTINGS_SITEURL: str = "http://localhost:8065/"
Это для чего, и чем отличается от `WEBHOOK_HOST_URL`?

2023-10-28 17:42 UTC, NiKuma0 commented on src/bot/plugins/week_routine.py
> +        await notify_service.change_user_status(user_id)
Зачем в отдельный метод упаковывать?

2023-10-28 17:42 UTC, NiKuma0 commented on src/bot/plugins/week_routine.py
> +            self.driver.create_post(event.body["channel_id"], f"Webhook '{event.webhook_id}' triggered!")
Не очень ясно зачем этот пост создавать...

2023-10-28 17:42 UTC, NiKuma0 commented on src/bot/plugins/week_routine.py
>              notify_service.notify_all_users,
В этом сервисе используется `create_post` - лучше будет `direct_message`.

2023-10-28 17:42 UTC, NiKuma0 commented on src/bot/plugins/week_routine.py
>  LOGGER = structlog.get_logger()
Это не константа
```suggestion
logger = structlog.get_logger()
```

2023-10-30 05:48 UTC, KlavaD commented on src/bot/plugins/week_routine.py
> +        await notify_service.change_user_status(user_id)
Написала в пачке

2023-10-30 21:37 UTC, NiKuma0 approved these changes

2023-10-31 05:19 UTC, NiKuma0 approved these changes

2023-10-31 05:19 UTC, merged