Заглушка для бота
Studio-Yandex-Practicum/RandomCoffeeBot pull request #9
Opened 2023-07-19 12:43 UTC by tmbkv

Написал заглушку для бота в файле bot.py, на основе стандартной библиотеки mmpy_bot.
Создал файл main.py для запуска бота

2023-07-19 13:42 UTC, NiKuma0 requested changes

2023-07-19 13:42 UTC, NiKuma0 commented on src/bot/bot.py
> +        self.driver.reply_to(message, "Привет, я помогу организовать тебе random coffee")
Тут не должно быть `await`?

2023-07-19 13:42 UTC, NiKuma0 commented on src/bot/main.py
> +bot = Bot(
Сделай отдельную функцию `init_bot`, `start_bot` и точку входа.

2023-07-19 13:42 UTC, NiKuma0 commented on src/bot/main.py
> +    plugins=[MyPlugin()],  # Add your own plugins here.
Убери комментарии.

2023-07-19 13:57 UTC, tmbkv commented on src/bot/bot.py
> +        self.driver.reply_to(message, "Привет, я помогу организовать тебе random coffee")
Да, точно, добавлю

2023-07-24 19:32 UTC, tmbkv reviewed
Доработана заглушка для бота

2023-07-24 20:29 UTC, NiKuma0 approved these changes
Поправь конфликт

2023-07-24 20:29 UTC, NiKuma0 commented on Dockerfile
> +EXPOSE 8000
Лучше будет открывать порты при запуске или в `docker-compose`

2023-07-25 18:40 UTC, tmbkv commented
Добавил финальную версию заглушки. Заглушка протестирована, все работает. Замечания устранены

2023-07-26 12:35 UTC, NiKuma0 approved these changes

2023-07-26 13:30 UTC, merged